
server:
  port: 8088
  servlet:
    context-path: /yf

spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.105.165.12:3306/aipeng?useUnicode=true&characterEncoding=utf-8&autoReconnect=true
    username: root
    password: \!234Qwer
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  http:
    encoding: UTF-8
      
